## Basic Configuration
baseURL = "https://doingstuff.dev"
languageCode = "en-us"
title = "Doing Stuff"

theme = "hyde-hyde-hyde"

## Hugo Built-in Features
# googleAnalytics = ""
enableRobotsTXT = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    noClasses = true
    noHl = true
    style = 'friendly'
    tabWidth = 4


[outputs]
  home = ["HTML", "RSS", "JSON"]

## Site Settings
[params]
    author = "Morgan Creekmore"
    description = "A blog about stuff"
    #authorimage = "/img/author.jpg"
    dateformat = "Jan 2, 2006"
    themeColor = "theme-base-darkblue"
    error404image = "img/lost.gif"

    # https://www.goatcounter.com/
    goatcounter = "grbt-doingstuff"

    # https://mermaid.js.org/
    # mermaid = true # enabled per page to reduce loading
    mermaid_theme = "default"
    mermaid_align = "center"

    relatedPosts = false
    postNavigation = true

    toc = "tocbot"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Search"
    identifier = "search"
    weight = 200
    url = "/search/"
[[menu.main]]
    name = "RSS"
    identifier = "rss"
    weight = 300
    url = "/posts/index.xml"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 400
    url = "https://morgancreekmore.me/"
