base_url = "https://doingstuff.dev"

theme = "doingstuff-zola"

title = "Doing Stuff"
description = "Doing Stuff Blog"
author = "Morgan Creekmore"

compile_sass = true
build_search_index = true
generate_feeds = true

taxonomies = [
    {name = "tags", rss = false},
]

ignored_content = ["**/.obsidian/**", "**/_templates/**"] # ignore the .obsidian and __templates folder for publishing

[search]
include_date = true
index_format = "elasticlunr_json"

[markdown.highlighting]
extra_themes = ["syntaxes/cobalt2.json"] # https://github.com/robertoachar/vscode-theme-cobalt2/blob/master/theme/cobalt2.json
theme = "Cobalt"

[extra]
menu = [
    {url = "/posts", name = "Posts"},
    {url = "/atom.xml", name = "RSS"},
]

author_url = "https://creekmore.dev"

# https://www.goatcounter.com/
goatcounter = "grbt-doingstuff"

# https://github.com/francoischalifour/medium-zoom
jszoom = false

