base_url = "https://doingstuff.dev"

theme = "doingstuff-zola"

title = "Doing Stuff"
description = "A blog about stuff"
author = "Morgan Creekmore"

compile_sass = true
build_search_index = true
generate_feeds = true

taxonomies = [
    {name = "tags", rss = false},
]

ignored_content = ["**/.obsidian/**", "**/_templates/**"] # ignore the .obsidian and __templates folder for publishing

[search]
include_date = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
extra_syntaxes_and_themes = ["syntaxes"]
highlight_theme = "cobalt2"

[extra]
menu = [
    {url = "/posts", name = "Posts"},
    {url = "/atom.xml", name = "RSS"},
    {url = "https://creekmore.dev", name = "About"},
]

author_url = "https://graphics.social/@gamingrobot"

# https://www.goatcounter.com/
goatcounter = "grbt-doingstuff"

# https://github.com/francoischalifour/medium-zoom
jszoom = false

# https://mermaid.js.org/
mermaid_theme = "default"
mermaid_theme_dark = "dark"
mermaid_align = "center"

