base_url = "https://doingstuff.dev"

theme = "hyde-hyde-hyde-zola"

title = "Doing Stuff"
description = "A blog about stuff"
author = "Morgan Creekmore"

compile_sass = true
build_search_index = true
generate_feed = true

taxonomies = [
    {name = "tags", rss = false},
]

[search]
include_date = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
extra_syntaxes_and_themes = ["syntaxes"]
highlight_theme = "cobalt2"

[extra]
menu = [
    {url = "/posts", name = "Posts"},
    {url = "/atom.xml", name = "RSS"},
    {url = "/pages/about", name = "About"},
]

author_url = "https://infosec.exchange/@gamingrobot"

# https://www.goatcounter.com/
goatcounter = "grbt-doingstuff"

# https://mermaid.js.org/
mermaid_theme = "default"
mermaid_align = "center"

